name: .NET Tests

on:
  push:
    branches:
      - HomeWork_1_6_UnitTests  # Запускать при пуше в ветку HomeWork_1_6_UnitTests
  pull_request:
    branches:
      - HomeWork_1_6_UnitTests  # Запускать при создании pull request в ветку HomeWork_1_6_UnitTests

jobs:
  test:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Клонируем репозиторий

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'  

      - name: Restore dependencies
        run: dotnet restore  # Восстанавливаем зависимости

      - name: Build
        run: dotnet build --configuration Release --no-restore  # Собираем проект

      - name: Run tests
        run: dotnet test --no-build --verbosity normal  # Запускаем тесты
